# Name: robo-ar601
# Use melodic base image with ubuntu
FROM robolab.innopolis.university:5000/base-yefan:latest
MAINTAINER Vadim Rashitov

RUN mkdir -p /home/catkin_ws/src/yefan
COPY . /home/catkin_ws/src/yefan/

RUN /bin/bash -c '. /opt/ros/melodic/setup.bash; cd /home/catkin_ws; catkin_make'
EXPOSE 11345-11355
