topic_gravity_generalized_forces:   "/yefan/srv/drake_gravity_generalized_forces"
topic_inertia_matrix:               "/yefan/srv/drake_inertia_matrix"
topic_inverse_dynamics:             "/yefan/srv/drake_inverse_dynamics"
topic_jacobian_spatial:             "/yefan/srv/drake_jacobian_spatial"
topic_linearization:                "/yefan/srv/drake_linearization"
topic_lqr_costs:                    "/yefan/srv/drake_lqr_costs"
topic_lqr_gain:                     "/yefan/srv/drake_lqr_gain"
topic_inverse_kinematics:           "/yefan/srv/ik"
topic_forward_kinematics:           "/yefan/srv/fk"
topic_trajectory_planner:           "/yefan/srv/trajectory"